# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/inkreu',
                'doc_host': 'https://klmrgrss.github.io',
                'git_url': 'https://github.com/klmrgrss/inkreu',
                'lib_path': 'inkreu'},
  'syms': {'inkreu.core': {'inkreu.core.foo': ('core.html#foo', 'inkreu/core.py')}}}
